title: Shivangi Rastogi
logo: /assets/img/Shivangi_Rastogi.jpg
description: Data Science Aspirant<br><br>Data Analyst and ETL/Data Testers with 11 years of Professional Expereience. Data Science aspirant and learner with post graduate program in AI and ML from Purdue University, USA. <br><br><a href="https://www.linkedin.com/in/shivangirastogi/">View my LinkedIn Profile</a> 

show_downloads: true
theme: jekyll-theme-minimal
