title: Shivangi Rastogi
logo: /assets/img/Shivangi_Rastogi.jpg
description: Data Science Learner
show_downloads: true
theme: jekyll-theme-minimal
social-network-links:
  email: "shivangi.move@gmail.com"
  linkedin: https://www.linkedin.com/in/shivangirastogi/
