title: Shivangi Rastogi
logo: /assets/img/Shivangi_Rastogi.jpg
description: >
 <br>
 Data Science Learner
 <br><br>
 Data Analyst and ET/Data Testers with 11 years of Professional Expereience. 
 Data Science aspirant and learner with post graduate program in AI and ML from Purdue University, USA.
 <br><br>
 <a href="https://www.linkedin.com/in/shivangirastogi/">View my LinkedIn Profile</a> 
 <a href="shivangi.move@gmail.com"> Contact Email Id</a> 
 Contact Number : <a href="+1 614-973-0358"></a> 

show_downloads: true
theme: jekyll-theme-minimal
